docs/docs/getting-started/tutorial.md

- fix multiple typos
- fix grammar to improve readability

docs: fix grammar & typos in `tutorial.md`

---

docs/docs/getting-started/installation.md

- corrects typo from `runnnig` to `running`
- removes redundant `using`
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

docs: fix typo & readability  in `installation.md`

---

.gitignore
docs/docs/templates/reference/filters.md
spec/marten/template/filter/join_spec.cr
spec/marten/template/filter/split_spec.cr
src/marten/template/filter.cr
src/marten/template/filter/join.cr
src/marten/template/filter/split.cr

I've added two new filters, filter specs and additions to docs/filters to add the `join` and `split` filter functionality. My first contribution here, so please give brutal feedback (with a crystal, marten or general contributor lens).

Add support for split and join template filters #63

---

docs/docs/templates/reference/tags.md
spec/marten/template/tag/with_spec.cr
spec/marten/template/tag_spec.cr
src/marten/template/tag.cr
src/marten/template/tag/with.cr

I've added a `with` tag to assign variables locally within the template.
I'm not quite sure about the last test case if the order should matters.  Maybe it would be better to first look in the context if any variable name is already defined and shadow the outer variable only after assignment was done.
Closes #86

Implement with tag for template

---

docs/docs/development/reference/management-commands.md
spec/marten/cli/manage/command/new_spec.cr
src/marten/cli/manage/command/new.cr
src/marten/cli/manage/command/new/context.cr
src/marten/cli/manage/command/new/templates/project/config/settings/base.cr.ecr
src/marten/cli/manage/command/new/templates/project/shard.yml.ecr

This commit adds the --database option to the new command.
By default when the option is not presented the sqlite3 database will be selected, otherwise the respective database which was choosen, i.e. the shard.yml file will be configured to include the shard for the specific database.
If MySql or Postgresql is selected the config/base.cr will use `localhost` as host and `<project_name>_db` as the database name. The user and password config will be written as a comment to `config/base.cr` as we can't make assumptions.
Closes #103

Add --database to new command

---

docs/docs/development/management-commands.md
docs/docs/development/reference/management-commands.md
spec/marten/cli/manage/command/clearsessions.cr
spec/marten/http/session/store/base_spec.cr
spec/marten/http/session/store_spec.cr
src/marten/cli/manage/command/clearsessions.cr
src/marten/http/session/store/base.cr
src/marten/http/session/store/cookie.cr

Adds a new abstract method `clear_expired_entries` to `Marten::HTTP::Session::Store::Base`.
Additionally a new CLI command clearsessions was added, which calls `clear_expired_entries` on all registered session stores

Add command to remove expired sessions

---

src/marten/cli/templates/auth/templates/app/templates/password_update.html.ecr

I accidentally added an unncessary email field to the password update form, which is not required

Remove unncessary input field from password update form

---

docs/docs/development/reference/settings.md
spec/marten/conf/global_settings/csrf_spec.cr
spec/marten/handlers/concerns/request_forgery_protection_spec.cr
src/marten/conf/global_settings/csrf.cr
src/marten/handlers/concerns/request_forgery_protection.cr

This PR adds the option to store the CSRF token in a session. The session key is also changeable, but set to `csrftoken` by default.
Closes #66

Use csrf session

---

src/marten/db/query/sql/query.cr

This line seems to be duplicated with `@distinct = true` on line 167 (169 previously).
If I'm wrong just close this PR

Removes duplicated assignment

---

spec/marten/handlers/record_create_spec.cr
spec/marten/handlers/record_update_spec.cr
spec/marten/handlers/schema_spec.cr
src/marten/cli/templates/auth/templates/spec/handlers/password_reset_initiate_handler_spec.cr.ecr
src/marten/cli/templates/auth/templates/spec/handlers/password_update_handler_spec.cr.ecr
src/marten/cli/templates/auth/templates/spec/handlers/sign_in_handler_spec.cr.ecr
src/marten/cli/templates/auth/templates/spec/handlers/sign_up_handler_spec.cr.ecr
src/marten/handlers/schema.cr

Proof of concept for #167.
I tested it locally and everything works. It also fixes [Turbo](https://turbo.hotwired.dev) content update.
The only breaking case is that if some front-end JS code relies on the response status, which is unlikely as it's not an API call, but HTML rendering.

Return 422 on invalid form submit

---

docs/docs/schemas/introduction.md

I found that it was a bit difficult to find the topic of schema errors in the template. I created an extra section for it to find it more easier in the sidebar, added an example for `schema.field_name.errored?` and added a few words about how to use it.
I was also thinking about how to add a reference from the template introduction, but I think that's to off-topic there.

Emphasise the topic schema in templates

---

spec/marten/template/tag/for/loop_spec.cr
src/marten/template/tag/for/loop.cr

Used modulo 2 to check for "even-ness". Zero is considered as [even](https://en.wikipedia.org/wiki/Parity_of_zero).
https://github.com/martenframework/marten/issues/201

add `odd?` and `even?` to the loop tag

---

docs/docs/assets/introduction.md
spec/marten/conf/global_settings/assets_spec.cr
spec/marten/middleware/asset_serving_spec.cr
src/marten/conf/global_settings/assets.cr
src/marten/middleware/asset_serving.cr

Allow changing the `max-age` value in the settings. It still retain the default `3600s` if `max_age` is not configured.
https://github.com/martenframework/marten/issues/221

Assets max age

---

spec/marten/template/tag/csrf_input_spec.cr
spec/marten/template/tag_spec.cr
src/marten/template/tag.cr
src/marten/template/tag/csrf_input.cr

Added a new `csrf_input` tag that would take the output of the `csrf_token` tag and create the html hidden input that uses that output as value.
https://github.com/martenframework/marten/issues/200

csrf-input tag that uses csrf_token as value

---

docs/docs/development/reference/settings.md
src/marten/cli/manage/command/new/templates/project/config/settings/development.cr.ecr

Set log level to `Log::Severity::Debug` in `config/settings/development.cr` when a new project is created and mention this in the documentation.
fixes https://github.com/martenframework/marten/issues/239

default development log level `Log::Severity::Debug`

---

src/marten/server.cr

This PR refactors the HTTP server initialization in Marten to facilitate its use in a serverless environment. By separating the server instance creation and the handler configuration, users can now easily access the handlers independently of the server instance.
- **Refactored `self.instance` method**: 
- Moved handler configuration to a separate `self.handlers` method.
- `self.instance` now calls `self.handlers` for handler configuration.
```crystal
def self.instance : ::HTTP::Server
@@instance ||= ::HTTP::Server.new(handlers)
end
def self.handlers
[
::HTTP::ErrorHandler.new,
Handlers::Logger.new,
Handlers::Error.new,
Handlers::Middleware.new,
Handlers::Routing.new,
]
end
```
The primary motivation for this change is to support hosting Marten in a serverless environment. In such …

Extract Marten::Server handlers into separate method

---

docs/docs/handlers-and-http/reference/generic-handlers.md
docs/versioned_docs/version-0.4/handlers-and-http/reference/generic-handlers.md
docs/versioned_docs/version-0.5/handlers-and-http/reference/generic-handlers.md

All current docs that are showing an example of how to add a context variable via the `before_render` macro were missing a colon before the function specifier

Fix context example for template handler

---

docs/docs/handlers-and-http/reference/generic-handlers.md

This update improves the consistency of record generic handlers. 
Key changes:
- Use `Article` as reference record
- Use `Article<action>Schema` naming for schemas
- Always refer to **_articles/_** directory for `template_name`.
- Always make the `model` macro the first configuration in the handler
Considerations I didn't rework: Unify the `success_route_name`.

Make record generic handler more unified

---

spec/marten/spec/client_spec.cr
src/marten/http/session/store/base.cr
src/marten/middleware/session.cr

Now we can set the expiration time for cookies.
```cr
session.expires = {TIME IN SECONDS}
```
Note: _Value 0 is would make the session last as long as the browser is open._

Added expires property to the session

---

src/marten/cli/manage/command/routes.cr

Fixes the name display of nested routes when using `marten routes`. 
```crystal
Marten.routes.draw do
path "/admin", Admin::ROUTES, name: "admin"
end
module Admin
ARTICLE_ROUTES = Marten::Routing::Map.draw do
path "/", Admin::ArticleListHandler, name: "list"
path "/create", Admin::ArticleCreateHandler, name: "create"
path "/<pk:int>", Admin::ArticleDetailHandler, name: "detail"
end
ROUTES = Marten::Routing::Map.draw do
path "/articles", ARTICLE_ROUTES, name: "article"
end
end
```
Would produce
```
/articles/ [article:list] › Admin::ArticleListHandler
/articles/create [article:create] › Admin::ArticleCreateHandler
/articles/<pk:int> [article:detail] › Admin::ArticleDetailHandler
```
instead of
```
/admin/articles/ [admin:article:list] › Admin::ArticleListHandler
/admin/articles/create …
```

Bugifx: Fix display of nested routes

---

docs/docs/development/reference/settings.md
docs/docs/handlers-and-http/reference/middlewares.md
spec/marten/conf/global_settings_spec.cr
spec/marten/middleware/referrer_policy_spec.cr
src/marten/conf/global_settings.cr
src/marten/middleware/referrer_policy.cr

This adds a new Referrer-Policy. If active the middleware will add a Referrer-Policy header to the response if not already defined
#244

Add middleware for Referrer-Policy

---

spec/marten/db/field/many_to_one_spec.cr
spec/marten/db/field/one_to_one_spec.cr
spec/marten/db/field/one_to_one_spec/models/comment.cr
spec/marten/db/query/related_set_spec.cr
src/marten/db/field/many_to_one.cr
src/marten/db/field/one_to_one.cr
src/marten/db/model/querying.cr
src/marten/db/query/related_set.cr

With this update, child objects will now reference the already-fetched parent, avoiding redundant queries and improving performance.
Closes https://github.com/martenframework/marten/issues/265

Avoid Unnecessary Database Query on Back Relations

---

docs/docs/development/how-to/configure-database-backends.md
spec/marten/conf/global_settings/database_spec.cr
spec/marten/conf/global_settings_spec.cr
src/marten.cr
src/marten/conf/global_settings.cr
src/marten/conf/global_settings/database.cr

Add functionality so one can configure a database from a URL.
Fixes #257

Config db from url

---

docs/docs/templates/reference/tags.md
spec/marten/template/tag/localize_spec.cr
spec/marten/template/tag_spec.cr
spec/test_project/locales/en.yml
src/marten/locales/de.yml
src/marten/locales/en.yml
src/marten/template/tag.cr
src/marten/template/tag/localize.cr

This PR adds a `localize` template tag which allows the user to localize Numbers, Dates and DateTimes
#273

Add `localize` template tag

---

docs/docs/models-and-databases/reference/query-set.md
spec/marten/db/model/querying_spec.cr
spec/marten/db/query/prefetcher_spec.cr
spec/marten/db/query/set_spec.cr
src/marten/db/errors.cr
src/marten/db/model/querying.cr
src/marten/db/query/prefetcher.cr
src/marten/db/query/set.cr

This change introduces the option to provide a custom query for `#prefetch`, e.g.:
```crystal
qs = List.prefetch(:items, Item.order(:position))
```
The type of custom query must match the related type, otherwise an exception is thrown.
#264

Add custom query for prefetching

---

docs/docs/models-and-databases/validations.md

While reading [Field validation rules](https://martenframework.com/docs/models-and-databases/validations#field-validation-rules), I found a statement that appears to be incorrect.
- fields using `blank: true` won't accept empty values
This contradicts the explanation in [fields#blank](https://martenframework.com/docs/models-and-databases/reference/fields#blank).
The correct explanation should be either
- fields using `blank: true` accept empty values
- fields using `blank: false` won't accept empty values
The latter is described earlier in this document, so I have fixed the explanation for `blank: true`.

Fix `blank: true` description

---

spec/marten/http/request_spec.cr
src/marten/http/request.cr

This change fixes an issue where GET/POST requests with the `Content-Type: application/json` header
and an empty body would raise a `JSON::ParseException: unexpected token '<EOF>' at line 1, column 1.`
The fix adds a check to ensure the request body is not empty before attempting to parse it as JSON.
<details><summary>Exception details</summary>
<pre>
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
from /opt/homebrew/Cellar/crystal/1.16.2/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
from /opt/homebrew/Cellar/crystal/1.16.2/share/crystal/src/json/parser.cr:69 in 'unexpected_token'
from /opt/homebrew/Cellar/crystal/1.16.2/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
from /opt/homebrew/Cellar/crystal/1.16.2/share/crystal/src/json/parser.cr:13:12 …

Support requests with `Content-Type: application/json` and empty body

---

src/marten/cli/manage/command/new/templates/shared/.editorconfig.ecr

At least from the example. Here's proof from a new project:
```cmd
renich@desktop myproj$ cat .editorconfig 
root = true
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
[*.cr,*.ecr]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
[*.md]
trim_trailing_whitespace = false
[Makefile]
indent_style = tab
renich@desktop myproj$ editorconfig $( readlink -f seed.cr )
charset=utf-8
end_of_line=lf
insert_final_newline=true
trim_trailing_whitespace=true
renich@desktop myproj$ cat .editorconfig 
root = true
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
[*.{cr,ecr}]
charset = utf-8
end_of_line = lf
insert_final_newline = …
```

Fix incompatible list in editorconfig

---

spec/marten/db/query/page_spec.cr
spec/marten/db/query/paginator_spec.cr
src/marten/db/query/page.cr
src/marten/db/query/paginator.cr

Adds a `total_count` method that returns the total number of records in the queryset without applying pagination.
This is useful for paginators that need both the total number of pages and the total record count. Instead of recalculating the total size repeatedly, this method centralizes and reuses that logic.
Inspired by [kaminari](https://github.com/kaminari/kaminari/blob/ca4a5dcfce40ede7990ebfe00a12f21e78e910d9/kaminari-activerecord/lib/kaminari/activerecord/active_record_relation_methods.rb#L17)

query: Add total_count method to support pagination

---

spec/marten/db/query/many_to_many_set_spec.cr
spec/test_project/models/order.cr
spec/test_project/models/product.cr
src/marten/db/query/many_to_many_set.cr

If a related m2m model has no `id` field as pk and it is added to the m2m relation twice following error is raised:
```bash
Error: undefined method 'id' for Country
```

Fix `ManyToManySet#add` if an existing relation has no `id` field

---

docs/docs/schemas/reference/fields.md

I tried the schema array field and it did not work as described in the documentation. Figured it needs the `:array` type specifier, as other fields too.

Fix schema array documentation
